version: '3.3'

# starts 4 docker containers running minio server instances.
# using nginx reverse proxy, load balancing, you can access
# it through port 9000.
services:
  minio1:
    image: minio/minio:RELEASE.2021-06-07T21-40-51Z
    hostname: minio1
    volumes:
      - ./data1-1:/data1
      - ./data1-2:/data2
    ports:
      - "9000:9000"
    expose:
      - "9000"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server http://10.1.1.{1...4}0/data{1...2}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

 
volumes:
  data1-1:
  data1-2:
 
